steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'cloud_trainer.dockerfile', '-t', 'gcr.io/dtumlops-374413/trainer:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/dtumlops-374413/trainer:latest']
timeout: 4000s